# Generated by Django 4.0.1 on 2022-01-20 14:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('p_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='player 1')),
                ('p_2', models.CharField(blank=True, max_length=255, null=True, verbose_name='player 2')),
                ('p_1_shoot_ts', models.CharField(blank=True, max_length=255, null=True, verbose_name='player 1 shoot ts')),
                ('p_2_shoot_ts', models.CharField(blank=True, max_length=255, null=True, verbose_name='player 2 shoot ts')),
                ('winner', models.CharField(blank=True, max_length=255, null=True, verbose_name='winner')),
            ],
        ),
    ]
